# Generated by Django 5.0.6 on 2024-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_details_gender_details_message_details_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='message',
        ),
        migrations.RemoveField(
            model_name='details',
            name='photo',
        ),
        migrations.AddField(
            model_name='details',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
    ]
