# Generated by Django 5.0.6 on 2024-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=100)),
                ('DeptDuration', models.IntegerField()),
                ('DeptFees', models.CharField(max_length=100)),
                ('DeptFaculty', models.IntegerField()),
                ('password', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
