# Generated by Django 5.0 on 2024-07-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Contactno', models.BigIntegerField(blank=True, default=0, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
